services:
    frontend:
        image: "node"
        volumes:
            - "./frontend:/var/www/html"
        working_dir: "/var/www/html"
        environment:
            NEXT_PUBLIC_BASE_URL: ${FRONTEND_URL}
            NEXT_PUBLIC_BACKEND_URL: ${BACKEND_URL}
            NEXT_PUBLIC_BACKEND_WS_URL: ${BACKEND_WS_URL}
        ports:
            - "3000:3000"
        command: bash -c "npm ci && npm run dev"
    backend:
        image: "node"
        volumes:
            - "./backend:/var/www/html"
        working_dir: "/var/www/html"
        environment:
            PORT: ${BACKEND_PORT}
            FRONTEND_URL: ${FRONTEND_URL}
        ports:
            - "3001:3001"
        command: bash -c "npm ci && npm run dev"
