version: "3.8"
services:
    frontend:
        image: "node"
        volumes:
            - "./frontend:/var/www/html"
        working_dir: "/var/www/html"
        environment:
            NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        ports:
            - "3000:3000"
        command: bash -c "npm install && npm run dev"
    backend:
        image: "node"
        volumes:
            - "./backend:/var/www/html"
        working_dir: "/var/www/html"
        ports:
            - "3001:3001"
        command: bash -c "npm install && npm run dev"
